In [1]:
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import csv

In [2]:
#estudantes = csv.reader(open("Estudantes_CRP_tratado.csv"),delimiter=';')
#historico  = csv.reader(open("Historico_CRP.csv"),delimiter=';')
estudantes = pd.read_csv(("Estudantes_CRP_tratado.csv"),delimiter=';', low_memory=False)
historico = pd.read_csv(("Historico_CRP.csv"),delimiter=';')
historicoV = pd.read_csv(("CRP_HistVelho.csv"),delimiter=';', low_memory=False)

In [3]:
CRPhisV = pd.DataFrame(historicoV)

In [4]:
CRPinfo = pd.DataFrame(estudantes)
CRPhis = pd.DataFrame(historico)

In [5]:
CRPhisNovo = pd.concat([CRPhisV, CRPhis], axis=0, verify_integrity=True, ignore_index = True)

In [6]:
CRPhisNovo.drop_duplicates()

,Campus,Identificador,Ano,Semestre,Cd_Disciplina,Codigo_Conceito,Nota,Faltas_Teorica,Faltas_Pratica
0,CRP,30003576,2014,1,ADE 101,NaN,50,2,0
1,CRP,30003576,2014,1,ADE 191,NaN,44,0,0
2,CRP,30003576,2014,1,CIC 100,NaN,60,4,0
3,CRP,30003576,2014,1,CRP 091,S,0,2,0
4,CRP,30003576,2014,1,CRP 191,NaN,65,0,0
...,...,...,...,...,...,...,...,...,...
159638,CRP,30009987,2021,1,SIN 323,T,NaN,NaN,NaN
159639,CRP,30009987,2021,1,SIN 352,T,NaN,NaN,NaN
159640,CRP,30009987,2021,1,SIN 392,T,NaN,NaN,NaN
159641,CRP,30009987,2021,1,SIN 394,,90.0,NaN,NaN
159642,CRP,30009987,2021,1,SIN 421,T,NaN,NaN,NaN

In [7]:

AlunosSIquery = CRPinfo.query('Codigo_Curso== 104' and 'Codigo_Curso== 105')
AlunosSI = pd.DataFrame(data=AlunosSIquery)

In [8]:
AlunosSI.to_csv("AlunosSI.csv")

In [9]:
matricula = CRPhisNovo['Identificador']
matriculaSI = AlunosSI['Identificador']
matriculaSI.to_csv("matriculasi.csv")

In [10]:
dfmat = pd.DataFrame(data = matriculaSI)

In [11]:
dfFim = pd.merge(AlunosSI, CRPhisNovo, how= 'outer', on = 'Identificador')
dfFim.dropna(subset=["Curso"])

,Campus_x,Identificador,Codigo_Curso,Curso,Ano_Admissao,Sem_Admissao,Codigo_Forma_Ingresso,Forma_Ingresso,Ano_Conclusao,Sem_Conclusao,...,Iniciacao CientÃ­fica,ExtensÃ£o,Campus_y,Ano,Semestre,Cd_Disciplina,Codigo_Conceito,Nota,Faltas_Teorica,Faltas_Pratica
0,CRP,30004155.0,105.0,Sistemas de Informacao - Noturno,2014.0,1.0,L,SISU - Sistema_de_Selecao_Unificada,2014.0,1,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CRP,30004170.0,105.0,Sistemas de Informacao - Noturno,2014.0,1.0,L,SISU - Sistema_de_Selecao_Unificada,2018.0,1,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CRP,30004183.0,105.0,Sistemas de Informacao - Noturno,2014.0,1.0,L,SISU - Sistema_de_Selecao_Unificada,2014.0,1,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CRP,30004216.0,105.0,Sistemas de Informacao - Noturno,2014.0,1.0,L,SISU - Sistema_de_Selecao_Unificada,2014.0,2,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CRP,30004221.0,105.0,Sistemas de Informacao - Noturno,2014.0,1.0,L,SISU - Sistema_de_Selecao_Unificada,2017.0,2,...,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5147,CRP,30009987.0,105.0,Sistemas de Informacao - Noturno,2021.0,1.0,R,RematrÃ­cula ...,NaN,NaN,...,N,N,CRP,2021,1,SIN 323,T,NaN,NaN,NaN
5148,CRP,30009987.0,105.0,Sistemas de Informacao - Noturno,2021.0,1.0,R,RematrÃ­cula ...,NaN,NaN,...,N,N,CRP,2021,1,SIN 352,T,NaN,NaN,NaN
5149,CRP,30009987.0,105.0,Sistemas de Informacao - Noturno,2021.0,1.0,R,RematrÃ­cula ...,NaN,NaN,...,N,N,CRP,2021,1,SIN 392,T,NaN,NaN,NaN
5150,CRP,30009987.0,105.0,Sistemas de Informacao - Noturno,2021.0,1.0,R,RematrÃ­cula ...,NaN,NaN,...,N,N,CRP,2021,1,SIN 394,,90.0,NaN,NaN
5151,CRP,30009987.0,105.0,Sistemas de Informacao - Noturno,2021.0,1.0,R,RematrÃ­cula ...,NaN,NaN,...,N,N,CRP,2021,1,SIN 421,T,NaN,NaN,NaN

In [142]:
alunoLog = CRPhisNovo.query('Cd_Disciplina == "SIN 130"')
alunoSI = alunoLog['Identificador']
HiSI = CRPhisNovo.merge(alunoSI)

In [111]:
#HiSI = CRPhisNovo.merge(dfmat)
HiSI.to_csv("HistoricoSICRP.csv")

In [143]:
HiSI.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12910 entries, 0 to 12909
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Campus           12910 non-null  object
 1   Identificador    12910 non-null  object
 2   Ano              12910 non-null  object
 3   Semestre         12910 non-null  object
 4   Cd_Disciplina    12910 non-null  object
 5   Codigo_Conceito  1786 non-null   object
 6   Nota             12673 non-null  object
 7   Faltas_Teorica   10817 non-null  object
 8   Faltas_Pratica   10817 non-null  object
dtypes: object(9)
memory usage: 1008.6+ KB

In [59]:
SIhis = pd.DataFrame(data = HiSI)

In [1]:
HiSI.query('Ano == "2014"'and 'Cd_Disciplina == "SIN 110")

SyntaxError: EOL while scanning string literal (Temp/ipykernel_3460/2841605626.py, line 1)